// AUTO-GENERATED by export_weights.py -- do not edit.
`ifndef NN_PARAMS_AUTO_SVH
`define NN_PARAMS_AUTO_SVH

`define NN_INPUT_SIZE   784
`define NN_HIDDEN1_SIZE 128
`define NN_HIDDEN2_SIZE 64
`define NN_OUTPUT_SIZE  10
`define NN_FRAC_BITS    16
`define NN_L0_M_Q   32'h00000015
`define NN_L1_M_Q   32'h00000098
`define NN_L2_M_Q   32'h0000008d

`endif
