"""
export_weights.py
=================
Thin wrapper around quantization.py.  Some flows want a *separate* "export" step
even though our quantizer already writes .mem files; keeping this here also
gives the user a place to add C header / NPY / Verilog `parameter` dumps if
they ever need a different downstream tool.

Currently it just:
  1. invokes quantize.main() with the user-supplied args
  2. writes a SystemVerilog include file `rtl/include/nn_params_auto.svh`
     with shape constants — handy when you re-train with different layer sizes.
"""
from __future__ import annotations
import argparse, os, json, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--ckpt", type=str, default="../results/mlp_mnist_best.pt")
    p.add_argument("--mem_dir", type=str, default="../mem")
    p.add_argument("--include_dir", type=str, default="../rtl/include")
    p.add_argument("--frac_bits", type=int, default=16)
    p.add_argument("--sample_idx", type=int, default=0)
    args = p.parse_args()

    # 1) run quantization
    cmd = [sys.executable, os.path.join(HERE, "quantization.py"),
           "--ckpt", args.ckpt,
           "--mem_dir", args.mem_dir,
           "--frac_bits", str(args.frac_bits),
           "--sample_idx", str(args.sample_idx)]
    print("[export] running:", " ".join(cmd))
    subprocess.check_call(cmd)

    # 2) emit a small SV include with the layer sizes
    qp = json.load(open(os.path.join(args.mem_dir, "quant_params.json")))
    os.makedirs(args.include_dir, exist_ok=True)
    out = os.path.join(args.include_dir, "nn_params_auto.svh")
    with open(out, "w") as f:
        f.write("// AUTO-GENERATED by export_weights.py -- do not edit.\n")
        f.write("`ifndef NN_PARAMS_AUTO_SVH\n`define NN_PARAMS_AUTO_SVH\n\n")
        f.write(f"`define NN_INPUT_SIZE   {qp['layers'][0]['in']}\n")
        f.write(f"`define NN_HIDDEN1_SIZE {qp['layers'][0]['out']}\n")
        f.write(f"`define NN_HIDDEN2_SIZE {qp['layers'][1]['out']}\n")
        f.write(f"`define NN_OUTPUT_SIZE  {qp['layers'][2]['out']}\n")
        f.write(f"`define NN_FRAC_BITS    {qp['frac_bits']}\n")
        for i, L in enumerate(qp['layers']):
            f.write(f"`define NN_L{i}_M_Q   32'h{int(L['M_q']) & 0xFFFFFFFF:08x}\n")
        f.write("\n`endif\n")
    print(f"[export] wrote {out}")


if __name__ == "__main__":
    main()
