// =============================================================================
// nn_accel_top.sv -- top-level wrapper of the MNIST MLP accelerator.
//
// Block diagram (see docs/architecture.md for the full picture):
//
//   host -> CSR (config_regs) -> main_fsm -> dma_loader -> [WSRAM, ASRAM_A/B,
//   BSRAM] -> compute_layer (stagger -> pe_array -> drain -> ppu) -> OSRAM
//
// The "DRAM" port is exposed at the top so the testbench or a real AXI master
// can supply weights/biases/inputs.
// =============================================================================

`timescale 1ns/1ps
`include "nn_params_auto.svh"

module nn_accel_top
    import nn_pkg::*;
(
    input  logic        clk,
    input  logic        rst_n,

    // -------- CSR bus (host) --------
    input  logic        reg_we,
    input  logic [7:0]  reg_addr,
    input  logic [31:0] reg_wdata,
    output logic [31:0] reg_rdata,
    output logic        irq,

    // -------- "DRAM" port (testbench-supplied) --------
    output logic        dram_re,
    output logic [31:0] dram_addr,
    input  logic [WSRAM_WORD_W-1:0] dram_rdata,

    // -------- output readback (host can also read OSRAM via CSR; for sim we
    //          expose the full vector) --------
    output logic [OUTPUT_SIZE*DATA_WIDTH-1:0] out_logits_packed,
    output logic        out_valid          // pulses when DONE
);

    // -------- CSR --------
    logic         start_pulse, soft_reset;
    logic         busy_top, done_top;
    logic [31:0]  input_ptr, output_ptr;
    logic         irq_en;

    config_regs u_csr (
        .clk(clk), .rst_n(rst_n),
        .reg_we(reg_we), .reg_addr(reg_addr),
        .reg_wdata(reg_wdata), .reg_rdata(reg_rdata),
        .start_pulse(start_pulse), .soft_reset(soft_reset),
        .busy(busy_top), .done(done_top),
        .input_ptr(input_ptr), .output_ptr(output_ptr),
        .irq_en(irq_en), .irq(irq)
    );

    wire core_rst_n = rst_n & ~soft_reset;

    // -------- main FSM --------
    logic [1:0]  cl_layer_id;
    logic        cl_start, cl_busy, cl_done;

    logic        dma_start;
    logic [1:0]  dma_dst_sel;
    logic [31:0] dma_src_addr, dma_dst_addr, dma_length;
    logic        dma_busy, dma_done;

    logic        src_b_l1, dst_b_l1, src_b_l2, dst_b_l2, src_b_l3, dst_b_l3;

    main_fsm u_fsm (
        .clk(clk), .rst_n(core_rst_n),
        .start(start_pulse), .busy(busy_top), .done(done_top),
        .cl_layer_id(cl_layer_id),
        .cl_start(cl_start), .cl_busy(cl_busy), .cl_done(cl_done),
        .dma_start(dma_start), .dma_dst_sel(dma_dst_sel),
        .dma_src_addr(dma_src_addr), .dma_dst_addr(dma_dst_addr),
        .dma_length(dma_length),
        .dma_busy(dma_busy), .dma_done(dma_done),
        .src_bank_l1(src_b_l1), .dst_bank_l1(dst_b_l1),
        .src_bank_l2(src_b_l2), .dst_bank_l2(dst_b_l2),
        .src_bank_l3(src_b_l3), .dst_bank_l3(dst_b_l3),
        .input_dram_ptr(input_ptr)
    );

    // -------- per-layer descriptor lookup ------------------------------------
    // Weight base addresses (in WSRAM packed words):
    //   fc1 at 0
    //   fc2 at HIDDEN1*INPUT  / N
    //   fc3 at fc2 + HIDDEN2*HIDDEN1 / N
    localparam int W_BASE_L1 = 0;
    // Each layer occupies ceil(OUT/N)*IN packed words in the WSRAM.
    localparam int W_BASE_L2 = WSRAM_L1_WORDS;
    localparam int W_BASE_L3 = WSRAM_L1_WORDS + WSRAM_L2_WORDS;

    // Bias bases (INT32 addresses):
    localparam int B_BASE_L1 = 0;
    localparam int B_BASE_L2 = HIDDEN1_SIZE;
    localparam int B_BASE_L3 = HIDDEN1_SIZE + HIDDEN2_SIZE;

    // requant multipliers come from the include file generated by export_weights.py.
    // We provide safe defaults so the design elaborates even without it.
    `ifndef NN_L0_M_Q
      `define NN_L0_M_Q 32'h0000_4000   // Q0.16 ~= 0.25
      `define NN_L1_M_Q 32'h0000_4000
      `define NN_L2_M_Q 32'h0000_4000
    `endif

    logic [15:0]               cl_in_size, cl_out_size;
    logic                      cl_relu;
    logic [REQ_WIDTH-1:0]      cl_m_q;
    logic [WSRAM_AW-1:0]       cl_w_base;
    logic [BSRAM_AW-1:0]       cl_b_base;
    logic                      cl_src_b, cl_dst_b, cl_dst_is_out;

    always_comb begin
        unique case (cl_layer_id)
            2'd0: begin // fc1
                cl_in_size    = INPUT_SIZE;
                cl_out_size   = HIDDEN1_SIZE;
                cl_relu       = 1'b1;
                cl_m_q        = `NN_L0_M_Q;
                cl_w_base     = W_BASE_L1[WSRAM_AW-1:0];
                cl_b_base     = B_BASE_L1[BSRAM_AW-1:0];
                cl_src_b      = src_b_l1;
                cl_dst_b      = dst_b_l1;
                cl_dst_is_out = 1'b0;
            end
            2'd1: begin // fc2
                cl_in_size    = HIDDEN1_SIZE;
                cl_out_size   = HIDDEN2_SIZE;
                cl_relu       = 1'b1;
                cl_m_q        = `NN_L1_M_Q;
                cl_w_base     = W_BASE_L2[WSRAM_AW-1:0];
                cl_b_base     = B_BASE_L2[BSRAM_AW-1:0];
                cl_src_b      = src_b_l2;
                cl_dst_b      = dst_b_l2;
                cl_dst_is_out = 1'b0;
            end
            default: begin // fc3
                cl_in_size    = HIDDEN2_SIZE;
                cl_out_size   = OUTPUT_SIZE;
                cl_relu       = 1'b0;
                cl_m_q        = `NN_L2_M_Q;
                cl_w_base     = W_BASE_L3[WSRAM_AW-1:0];
                cl_b_base     = B_BASE_L3[BSRAM_AW-1:0];
                cl_src_b      = src_b_l3;
                cl_dst_b      = dst_b_l3;
                cl_dst_is_out = 1'b1;
            end
        endcase
    end

    // -------- SRAMs ----------------------------------------------------------
    // Weight SRAM: 1 read port shared by DMA (write) and compute (read).
    logic                       w_en;
    logic                       w_we;
    logic [WSRAM_AW-1:0]        w_addr;
    logic [WSRAM_WORD_W-1:0]    w_din, w_dout;

    sram_sp #(.DATA_W(WSRAM_WORD_W), .DEPTH(WSRAM_DEPTH))
    u_wsram (.clk(clk), .en(w_en), .we(w_we),
             .addr(w_addr), .din(w_din), .dout(w_dout));

    // Bias SRAM (INT32)
    logic                       bsram_en, bsram_we;
    logic [BSRAM_AW-1:0]        bsram_addr;
    logic [BIAS_WIDTH-1:0]      bsram_din, bsram_dout;
    sram_sp #(.DATA_W(BIAS_WIDTH), .DEPTH(BSRAM_DEPTH))
    u_bsram (.clk(clk), .en(bsram_en), .we(bsram_we),
             .addr(bsram_addr), .din(bsram_din), .dout(bsram_dout));

    // Activation SRAM A and B
    logic                       a_en, a_we;
    logic [ASRAM_AW-1:0]        a_addr;
    logic [DATA_WIDTH-1:0]      a_din, a_dout;
    sram_sp #(.DATA_W(DATA_WIDTH), .DEPTH(ASRAM_DEPTH))
    u_asram_a (.clk(clk), .en(a_en), .we(a_we),
               .addr(a_addr), .din(a_din), .dout(a_dout));

    logic                       b_en, b_we;
    logic [ASRAM_AW-1:0]        b_addr;
    logic [DATA_WIDTH-1:0]      b_din, b_dout;
    sram_sp #(.DATA_W(DATA_WIDTH), .DEPTH(ASRAM_DEPTH))
    u_asram_b (.clk(clk), .en(b_en), .we(b_we),
               .addr(b_addr), .din(b_din), .dout(b_dout));

    // Output SRAM
    logic                       o_en, o_we;
    logic [OSRAM_AW-1:0]        o_addr;
    logic [DATA_WIDTH-1:0]      o_din, o_dout;
    sram_sp #(.DATA_W(DATA_WIDTH), .DEPTH(OSRAM_DEPTH))
    u_osram (.clk(clk), .en(o_en), .we(o_we),
             .addr(o_addr), .din(o_din), .dout(o_dout));

    // -------- DMA ------------------------------------------------------------
    logic                          dma_w_we, dma_a_we, dma_b_we, dma_o_we;
    logic [31:0]                   dma_w_a, dma_a_a, dma_b_a, dma_o_a;
    logic [WSRAM_WORD_W-1:0]       dma_w_d;
    logic [DATA_WIDTH-1:0]         dma_a_d;
    logic [BIAS_WIDTH-1:0]         dma_b_d;
    logic [DATA_WIDTH-1:0]         dma_o_d;
    logic                          dma_a_bank;

    dma_loader #(.WORD_W(WSRAM_WORD_W)) u_dma (
        .clk(clk), .rst_n(core_rst_n),
        .start(dma_start), .src_addr(dma_src_addr), .dst_addr(dma_dst_addr),
        .length(dma_length), .dst_sel(dma_dst_sel),
        .busy(dma_busy), .done(dma_done),
        .dram_addr(dram_addr), .dram_re(dram_re), .dram_rdata(dram_rdata),
        .w_we(dma_w_we), .a_we(dma_a_we), .b_we(dma_b_we), .o_we(dma_o_we),
        .w_addr(dma_w_a), .a_addr(dma_a_a), .b_addr(dma_b_a), .o_addr(dma_o_a),
        .w_din(dma_w_d),  .a_din(dma_a_d),  .b_din(dma_b_d),  .o_din(dma_o_d),
        .a_bank_sel(dma_a_bank)
    );

    // -------- compute_layer --------------------------------------------------
    logic        cl_a_re, cl_a_we;
    logic [ASRAM_AW-1:0] cl_a_addr;
    logic [DATA_WIDTH-1:0] cl_a_din;

    logic        cl_b_re, cl_b_we;
    logic [ASRAM_AW-1:0] cl_b_addr;
    logic [DATA_WIDTH-1:0] cl_b_din;

    logic        cl_w_re;
    logic [WSRAM_AW-1:0] cl_w_addr;

    logic        cl_bias_re;
    logic [BSRAM_AW-1:0] cl_bias_addr;

    logic        cl_o_we;
    logic [OSRAM_AW-1:0] cl_o_addr;
    logic [DATA_WIDTH-1:0] cl_o_din;

    compute_layer #(.N(ARRAY_SIZE), .DATA_W(DATA_WIDTH), .ACC_W(ACC_WIDTH))
    u_compute (
        .clk(clk), .rst_n(core_rst_n),
        .start(cl_start), .busy(cl_busy), .done(cl_done),
        .in_size(cl_in_size), .out_size(cl_out_size),
        .relu_en(cl_relu), .m_q(cl_m_q),
        .w_base(cl_w_base), .b_base(cl_b_base),
        .src_bank(cl_src_b), .dst_bank(cl_dst_b),
        .dst_is_output(cl_dst_is_out),
        .a_re(cl_a_re), .a_we(cl_a_we), .a_addr(cl_a_addr),
        .a_din(cl_a_din), .a_dout(a_dout),
        .b_re(cl_b_re), .b_we(cl_b_we), .b_addr(cl_b_addr),
        .b_din(cl_b_din), .b_dout(b_dout),
        .w_re(cl_w_re), .w_addr(cl_w_addr), .w_dout(w_dout),
        .bias_re(cl_bias_re), .bias_addr(cl_bias_addr), .bias_dout(bsram_dout),
        .o_we(cl_o_we), .o_addr(cl_o_addr), .o_din(cl_o_din)
    );

    // -------- SRAM port arbitration (DMA vs compute_layer) -------------------
    // Pure mux: DMA owns when dma_busy, otherwise compute_layer.
    assign w_en   = dma_busy ? dma_w_we           : cl_w_re;
    assign w_we   = dma_busy ? dma_w_we           : 1'b0;
    assign w_addr = dma_busy ? dma_w_a[WSRAM_AW-1:0] : cl_w_addr;
    assign w_din  = dma_w_d;

    assign bsram_en   = 1'b1;  // always-on read; cheap
    assign bsram_we   = dma_busy ? dma_b_we : 1'b0;
    assign bsram_addr = dma_busy ? dma_b_a[BSRAM_AW-1:0] : cl_bias_addr;
    assign bsram_din  = dma_b_d;

    // Activation A: DMA writes during LOAD_INPUT (bank A), compute reads/writes
    assign a_en   = (dma_busy && dma_a_we && !dma_a_bank) || cl_a_re || cl_a_we;
    assign a_we   = (dma_busy && dma_a_we && !dma_a_bank) || cl_a_we;
    assign a_addr = (dma_busy && dma_a_we && !dma_a_bank) ? dma_a_a[ASRAM_AW-1:0] : cl_a_addr;
    assign a_din  = (dma_busy && dma_a_we && !dma_a_bank) ? dma_a_d : cl_a_din;

    // Activation B: only compute touches it
    assign b_en   = cl_b_re || cl_b_we;
    assign b_we   = cl_b_we;
    assign b_addr = cl_b_addr;
    assign b_din  = cl_b_din;

    // Output SRAM
    assign o_en   = cl_o_we || 1'b1;          // always enable for readback
    assign o_we   = cl_o_we;
    assign o_addr = cl_o_addr;
    assign o_din  = cl_o_din;

    // -------- output readback ------------------------------------------------
    // For simulation we expose the entire OSRAM contents flattened.  Real
    // implementations would read these via the CSR bus or an AXI port.
    genvar gi;
    generate
        for (gi = 0; gi < OUTPUT_SIZE; gi++) begin : g_logits
            // peek into the output SRAM array hierarchically (sim only).
            assign out_logits_packed[gi*DATA_WIDTH +: DATA_WIDTH] = u_osram.mem[gi];
        end
    endgenerate
    assign out_valid = done_top;

endmodule
